[package]
name = "l15-exercise-use-the-result-type-to-handle-errors"
version = "0.1.0"
authors = ["h1z3y3 <gmzhaoyang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
